name: RDP

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 120

    steps:
      - name: Enable RDP
        shell: powershell
        run: |
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Restart-Service TermService -Force

      - name: Create User (Auto Password)
        shell: powershell
        run: |
          $username = "ayush"

          # Generate strong password (ALWAYS valid)
          $random = -join ((65..90) + (97..122) + (48..57) | Get-Random -Count 8 | % {[char]$_})
          $password = "A@" + $random + "9!"   # ensures uppercase, lowercase, number, special

          # Remove user if already exists (prevents error)
          if (Get-LocalUser -Name $username -ErrorAction SilentlyContinue) {
              Remove-LocalUser -Name $username
          }

          $secure = ConvertTo-SecureString $password -AsPlainText -Force
          New-LocalUser -Name $username -Password $secure
          Add-LocalGroupMember -Group "Administrators" -Member $username
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member $username

          echo "RDP_USER=$username" >> $env:GITHUB_ENV
          echo "RDP_PASS=$password" >> $env:GITHUB_ENV

      - name: Install Tailscale
        shell: powershell
        run: |
          Invoke-WebRequest https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi -OutFile ts.msi
          Start-Process msiexec.exe -ArgumentList "/i ts.msi /quiet /norestart" -Wait

      - name: Start Tailscale
        shell: powershell
        run: |
          $ts = "$env:ProgramFiles\Tailscale\tailscale.exe"

          & $ts up --authkey="${{ secrets.TAILSCALE_AUTH_KEY }}"

          Start-Sleep 10
          $ip = & $ts ip -4

          echo "IP=$ip" >> $env:GITHUB_ENV

      - name: Show RDP Info
        shell: powershell
        run: |
          Write-Host "===== RDP READY ====="
          Write-Host "IP: $env:IP"
          Write-Host "User: $env:RDP_USER"
          Write-Host "Password: $env:RDP_PASS"
          Write-Host "====================="

      - name: Wait Session
        shell: powershell
        run: |
          Start-Sleep -Seconds 5400
